(define (problem rush-hour-p01)
    (:domain rush-hour)
    (:objects
        x1 x2 x3 x4 x5 x6 y1 y2 y3 y4 y5 y6  - num
        red car1 car3 car4 car5 car6 car10 car13 car14 car16 car17 car18 - car
    )
    (:init

    
        (plusone x1 x2)
        (plusone x2 x3)
        (plusone x3 x4)
        (plusone x4 x5)
        (plusone x5 x6)
        (plusone x6 x7)
        (plusone y1 y2)
        (plusone y2 y3)
        (plusone y3 y4)
        (plusone y4 y5)
        (plusone y5 y6)
        (plusone y6 y7)
    
    
        ;; TODO

        (isOccupied 1 1)
        (isOccupied 4 1)
        (isOccupied 5 1)
        (isOccupied 6 1)
        (isOccupied 1 2)
        (isOccupied 3 2)
        (isOccupied 4 2)
        (isOccupied 5 2)
        (isOccupied 6 2)
        (isOccupied 1 3)
        (isOccupied 2 3)
        (isOccupied 3 3)
        (isOccupied 4 3)
        (isOccupied 5 3)
        (isOccupied 6 3)
        (isOccupied 1 4)
        (isOccupied 2 4)
        (isOccupied 3 4)
        (isOccupied 4 4)
        (isOccupied 5 4)
        (isOccupied 6 4)
        (isOccupied 4 5)
        (isOccupied 5 5)
        (isOccupied 6 5)
        (isOccupied 2 6)
        (isOccupied 3 6)
        (isOccupied 4 6)
        (carHead car1 1 2)
        (carTail car1 1 1)
        (carHead red 2 3)
        (carTail red 1 3)
        (carHead car3 3 4)
        (carTail car3 3 3)
        (carHead car4 4 4)
        (carTail car4 4 3)
        (carHead car5 5 4)
        (carTail car5 5 3)
        (carHead car6 6 4)
        (carTail car6 6 2)
        (carHead car10 4 6)
        (carTail car10 4 5)
        (carHead car13 6 1)
        (carTail car13 4 1)
        (carHead car14 5 2)
        (carTail car14 3 2)
        (carHead car16 2 4)
        (carTail car16 1 4)
        (carHead car17 6 5)
        (carTail car17 5 5)
        (carHead car18 3 6)
        (carTail car18 2 6)


    )
    (:goal (and
        (isOccupied 6 3)
        (isOccupied 5 3)
        (carHead red 6 3)
        (carTail red 5 3)
    ))
)
